---
- name: Preparation for facility reconciliation
  hosts: all
  remote_user: "{{ user }}"
  become: true
  tags: prep

  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

  tasks:

  - name: Ensure git
    yum:
      name: git
      state: present


  - name: install enterprise packages for enterprise linux
    yum: 
      name: epel-release
      state: installed


  - name: install redis packages
    yum: 
      name: redis
      state: installed


  # redis is running under systemd
  - name: start redis
    service:
      name: redis
      state: started
      enabled: yes


  - name: Download nodesource script for node v8
    get_url:
      url: https://rpm.nodesource.com/setup_8.x
      dest: $HOME/nodesource.sh
      mode: 0644


  - name: Install nodesource and node 8
    command: bash $HOME/nodesource.sh
    register: hello


  - debug:
      msg: "{{ hello.stdout_lines }}"


  - name: Ensure npm is latest
    npm: 
      name: npm
      state: present
      global: yes


  - name: Ensure native tools for native builds
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc-c++
      - make


# this ties the version to 3.6
# see https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-red-hat/
  - name: Add repository for mongo
    yum_repository:
      name: mongodb-org-3.6
      description: MongoDB Repository
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.6/x86_64/
      gpgcheck: yes
      gpgkey: https://www.mongodb.org/static/pgp/server-3.6.asc
      enabled: yes


# required for selinux
  # - name: install system packages
  #   package: name={{ item }} state=present
  #   become: true
  #   with_items:
  #     - libselinux-python
  #     - policycoreutils-python


# selinux not in use
  # - name: Configure SELinux
  #   seport:
  #     ports: 27017
  #     proto: tcp
  #     setype: mongod_port_t
  #     state: present


  - name: install mongodb
    yum:
      name: mongodb-org
      state: present
      # update_cache: yes
      # disable_plugin: fastestmirror


  # mongo is running under systemd
  - name: run mongodb
    service: 
      name: mongod
      state: started
      enabled: yes

